#
# Makefile for misc devices that really don't fit anywhere else.
#

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/lens/inc
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/inc
obj-$(CONFIG_HUAWEI_DSM)      += lens_dsm.o
obj-$(CONFIG_MTK_LENS)   += main/
obj-$(CONFIG_MTK_LENS)   += main2/
obj-$(CONFIG_MTK_LENS)   += sub/