# Makefile for the Himax touchscreen drivers.
# drivers/input/touchscreen
ccflags-y += -I$(srctree)/drivers/devkit/tpkit
obj-$(CONFIG_HIMAX_TS_KIT) += himax_platform.o himax_ic.o himax_fw_update.o himax_factory_test.o  himax_dsm.o himax_debug.o


