#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_FPSENSOR) += fpsensor_tee/
obj-$(CONFIG_CHIPSAILING) +=chipsailing_driver_tee/
obj-$(CONFIG_HAWEI_FINGERPRINT) += fingerprint/
