# GOODIX 
ccflags-y += -I$(srctree)/drivers/devkit/tpkit
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_ts.o 
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_gt1x_update.o
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_ts_test.o
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_ts_tools.o
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_dts.o
